application: goagent
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_g
  script: gae.application
  secure: optional

- url: /2
  script: gae.application
  secure: optional

- url: /fetch\.py
  script: gae.LegacyHandler.application
  secure: optional

- url: /.*
  script: gae.relay
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

libraries:
- name: pycrypto
  version: "latest"
