application: your_appid
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fetch\.py
  script: fetch.application
  secure: optional
  
error_handlers:
  - error_code: over_quota
    file: over_quota.html
